### ISSUE TITLE
Release for KSP 1.11?

### ISSUE THREAD

**Issue by SunSerega** [linuxgurugamer/ToolbarControl#13]
I think [this mod works](https://forum.kerbalspaceprogram.com/index.php?/topic/169509-19x-toolbar-controller-for-modders/&do=findComment&comment=3898456) for KSP 1.11.

Can you please update the last compatible version for CKAN? There are few mods that work with KSP 1.11, but fail to apply because of dependency on Toolbar Controller.

**Comment by linuxgurugamer** [comment]
I just updated Spacedock, it should be reflected in CKAN soon
