### ISSUE TITLE
Update released around 6/7 August seems to cause camera bug during launches, KSP 1.12.1

### ISSUE THREAD

**Issue by jtr99** [linuxgurugamer/ToolbarControl#14]
I'm running a KSP 1.12.1 game with about 80 mods installed and keeping everything up to date via CKAN. 

On either the 6th or the 7th of August 2021 there was an update released to ToolbarControl and I updated via CKAN as usual. Immediately afterwards I had a problem with the camera and with mouse clicks not registering during launches at KSC. Basically the camera is stuck underground at a strange angle, and most mouse clicks (e.g., to try to recover the vehicle) don't register. The symptoms were exactly as described in this old reddit thread: https://www.reddit.com/r/KerbalAcademy/comments/8315fd/camera_bug_at_rocket_launches/

By reverting the updates to ToolbarControl and Toolbar I found that the problem went away. 

Apologies that I can't be more specific or offer any theories about what caused the bug, but I thought you'd want to know. It's possible that you updated to match the new KSP 1.12.2 release and if I had been running 1.12.2 I would not have had this problem? If so please ignore my report.

**Comment by linuxgurugamer** [comment]
There was another update after that which fixed the problem.
But, you should always provide a log file when you report problems, also, posting on the forums usually gets a better response

**Comment by jtr99** [comment]
Thank you for the feedback and for your work in general. As you can probably tell, I am new to this! Will look at the forums first and will definitely include a log file if there is a next time. Cheers.
