### ISSUE TITLE
Broken Settings Window

### ISSUE THREAD

**Issue by maxmurder** [linuxgurugamer/ToolbarControl#15]
Running KSP Version 1.12.3, Ubuntu.

The settings window does not display correctly, no buttons are visible:

![20211225063742_1](https://user-images.githubusercontent.com/11280582/147387471-6b485efe-b001-465b-91cc-fc5bda1a17eb.jpg)

The window does not appear to be re-sizable or movable.

**Comment by linuxgurugamer** [comment]
I need a log file

**Comment by linuxgurugamer** [comment]
Also, that looks like the Advanced Fly By Wire, not ToolbarController

**Comment by linuxgurugamer** [comment]
FYI, you are probably missing dependencies
