### ISSUE TITLE
ToolbarControl.dll "File Version" metadata incorrect

### ISSUE THREAD

**Issue by rkagerer** [linuxgurugamer/ToolbarControl#17]
The latest build of ToolbarControl.dll has incorrect version metadata.  See: https://i.imgur.com/GHO5ZqX.png
I'm talking about the "File Version" and "Product Version" fields.

The old builds (as recently as 1.9.6) had the correct metadata.

Could you please correct this in the next build?

I realize you Linux users might ignore it, but on Windows this is a key way of checking which version of a DLL file is present.  The incorrect information is misleading and could lead to faulty troubleshooting.  Please don't strip the property altogether, it's very helpful to users.

**Comment by linuxgurugamer** [comment]
Confirmed, will get a new build out today
Thanks for reporting

**Comment by linuxgurugamer** [comment]
Fixed in new release
