### ISSUE TITLE
ArgumentException logspam

### ISSUE THREAD

**Issue by 7ranceaddic7** [linuxgurugamer/ToolbarControl#4]
So, yeah, getting these.  There are about 500K over a 20m span.
`[EXC 16:33:35.125] ArgumentException: Couldn't find custom parameter TC!
	GameParameters.CustomParams[TC] ()
	ToolbarControl_NS.ToolbarControl.OnGUI ()
[EXC 16:33:35.125] ArgumentException: Couldn't find custom parameter TC!
	GameParameters.CustomParams[TC] ()
	ToolbarControl_NS.ToolbarControl.OnGUI ()
[EXC 16:33:35.125] ArgumentException: Couldn't find custom parameter TC!
	GameParameters.CustomParams[TC] ()
	ToolbarControl_NS.ToolbarControl.OnGUI ()
[EXC 16:33:35.126] ArgumentException: Couldn't find custom parameter TC!
	GameParameters.CustomParams[TC] ()
	ToolbarControl_NS.ToolbarControl.OnGUI ()
[EXC 16:33:35.126] ArgumentException: Couldn't find custom parameter StateFundingSettings!
	GameParameters.CustomParams[StateFundingSettings] ()
	StateFunding.ViewManager.OnGUI ()
[EXC 16:33:35.126] ArgumentException: Couldn't find custom parameter TC!
	GameParameters.CustomParams[TC] ()
	ToolbarControl_NS.ToolbarControl.OnGUI ()
[EXC 16:33:35.126] ArgumentException: Couldn't find custom parameter PM!
	GameParameters.CustomParams[PM] ()
	PatchManager.PatchManagerClass.OnGUI ()
[EXC 16:33:35.126] ArgumentException: Couldn't find custom parameter TC!
	GameParameters.CustomParams[TC] ()
	ToolbarControl_NS.ToolbarControl.OnGUI ()
[EXC 16:33:35.126] ArgumentException: Couldn't find custom parameter BTWCustomParams!
	GameParameters.CustomParams[BTWCustomParams] ()
	BetterTimeWarp.BetterTimeWarp.OnGUI ()
[EXC 16:33:35.126] ArgumentException: Couldn't find custom parameter TC!
	GameParameters.CustomParams[TC] ()
	ToolbarControl_NS.ToolbarControl.OnGUI ()

**Comment by linuxgurugamer** [comment]
Rather useless report.  You didn't bother to give any other information, such as what version of KSP, which version of TC, which version of the other mods, etc.
Your problem is most likely related to running an old version of TC.  Update, and if it happens again, upload the output_log.txt.  Until then, I'm closing this as a non-report

**Comment by 7ranceaddic7** [comment]
And, I have since realized these are NOT caused by TC or PM.  Sorry I meant to delete/close this yesterday.
