### ISSUE TITLE
ToolbarControl button is visible in all scene

### ISSUE THREAD

**Issue by MaximeBrean** [linuxgurugamer/ToolbarControl#5]
The intro window state that the ToolbarControl button should be only visible in the SpaceCenter scene.
Using KSP 1.5.1 and Toolbar Controller 0.1.6.18, the button is available in all scenes.

Nothing really annoying here, just wanted to point a difference between intro and actual functionality.

**Comment by linuxgurugamer** [comment]
I'll have to update the code, it is supposed to be on all screens

**Comment by MaximeBrean** [comment]
For ones who don't play with blizzy's toolbar, is it possible to hide the ToolbarControl button from stock toolbar ?
As all button will always be visible in stock toolbar if blizzy's one is not available, I don't see the point of having the ToolbarControl button ... Or did I miss one functionality ?

**Comment by PiezPiedPy** [comment]
Also an option to enable/disable the icon when blizzy's toolbar is installed.

**Comment by 7ranceaddic7** [comment]
@MaximeBrean No, there is no option for this; it is PURPOSEFULLY prevented.  If TC is disabled from appearing in the stock toolbar, and someone where to later loaded BlizzyToolbar they would be unable to access the functionality of TC.

@PiezPiedPy Just send TC to Blizzy and don't configure Blizzy to display TC.

**Comment by linuxgurugamer** [comment]
What @7ranceaddic7  said.  I do need to update the text of the help window, though

**Comment by MaximeBrean** [comment]
@7ranceaddic7 What I mean by "hiding" is that TC button won't show because Blizzy's TB is not installed, not because I specifically configure it via options. Just an auto-hide depending on Blizzy's TB availability.
Of course, if Blizzy's TB is later installed, the button will then pop because it then has a purpose (selecting where each button will go).

**Comment by linuxgurugamer** [comment]
Thing is, the TC allows a button to be totally hidden, if desired.  Hiding this would prevent that and will most likely give me support headaches
