### ISSUE TITLE
Command Pods cause huge amount of lag in the VAB

### ISSUE THREAD

**Issue by AshtonDudley** [linuxgurugamer/ToolbarControl#7]
Placing a command pod down in the VAB causes huge amount of lag if I have ToolbarControl installed, removing ToolbarControl fixes the lag and a fresh install with just the mod also doesn't cause lag. I do have a very large amount of mods installed so I can't figure out which one is causing the problem.

[output_log.txt](https://github.com/linuxgurugamer/ToolbarControl/files/2545848/output_log.txt)

I can provide more info if needed, but even after updating the mods the issue still persists.

**Comment by AshtonDudley** [comment]
![image](https://user-images.githubusercontent.com/28170052/47965284-7c5cde80-e01b-11e8-8c4b-f26168242082.png)
![image](https://user-images.githubusercontent.com/28170052/47965287-841c8300-e01b-11e8-9982-5b027ca9d18f.png)
![image](https://user-images.githubusercontent.com/28170052/47965290-8aaafa80-e01b-11e8-98d3-50c2ee4f6de5.png)
Difference in preference between 0, 1 and 2 command pods

**Comment by linuxgurugamer** [comment]
You must have a mod installed which does something when a command pod is placed.  TC doesn't do anything other than interact with the toolbar

**Comment by linuxgurugamer** [comment]
Try installing only TC & CLB, test, and see what happens.

**Comment by AshtonDudley** [comment]
I tested it with just TC & CLB and there wasn't any sort of lag, I also tried with just my mods that use the toolbar and I also got no lag so its obviously not tooblar controller. I'm still not sure why deleting toolbar controller would stop the lag though..

**Comment by linuxgurugamer** [comment]
Deleting TC will cause other mods which depend on it to not load.  If one of those mods is causing the lag, then obviously the lag will not be there.
Thank you for testing.
What you need to do now is to start adding a few mods at a time until you see the lag

**Comment by AshtonDudley** [comment]
So it turns out DangIt is causing the problem, and removing the mod fixes the lag
